

WIDTH = 1600
HEIGHT = 1000

MAP_TILE_WIDTH = 500
MAP_TILE_HEIGHT = 500
TILE_SIZE = 10

MAP_CHUNK_SIZE = 11
ENTRANCE_SPACING = MAP_CHUNK_SIZE // 1
CHUNK_PIXEL_SIZE = TILE_SIZE * MAP_CHUNK_SIZE

SURFACE_WIDTH = TILE_SIZE * MAP_TILE_WIDTH
SURFACE_HEIGHT = TILE_SIZE * MAP_TILE_HEIGHT